# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PocketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('image_id', models.IntegerField()),
                ('src', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200, null=True)),
                ('caption', models.CharField(max_length=100, null=True)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'pocket_image',
                'verbose_name': 'pocket_image',
                'verbose_name_plural': 'pocket_images',
            },
        ),
        migrations.CreateModel(
            name='PocketItem',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('resolve_id', models.BigIntegerField(blank=True, null=True)),
                ('given_url', models.URLField()),
                ('given_title', models.CharField(max_length=200)),
                ('resolved_title', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.BooleanField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'not archived'), (1, 'archived'), (2, 'shoule be deleted')], default=0)),
                ('excerpt', models.CharField(blank=True, max_length=500, null=True)),
                ('is_article', models.BooleanField(default=1)),
                ('has_image', models.BooleanField(default=0)),
                ('has_video', models.BooleanField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('time_added', models.DateTimeField()),
                ('time_favorited', models.DateTimeField(null=True)),
                ('time_updated', models.DateTimeField(null=True)),
                ('time_read', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'pocket_item',
                'verbose_name': 'pocket_item',
                'verbose_name_plural': 'pocket_item',
            },
        ),
        migrations.CreateModel(
            name='PocketTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pocket_tag',
                'verbose_name': 'pocket_tag',
                'verbose_name_plural': 'pocket_tags',
            },
        ),
        migrations.CreateModel(
            name='PocketVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('video_id', models.IntegerField()),
                ('src', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200, null=True)),
                ('captions', models.CharField(max_length=100, null=True)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('vid', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'pocket_video',
                'verbose_name': 'pocket_video',
                'verbose_name_plural': 'pocket_videos',
            },
        ),
    ]
